In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("native_bayes_datasets.xlsx")
print(len(df))
df.head()

1188

  educ_class highest_graduation  loan_status  english_level  found_job
0          B                  Y            1              2          1
1          B                  Y            1              2          0
2          B                  Y            1              2          0
3          B                  Y            1              2          0
4          B                  I            1              3          0

In [30]:
# p(found_job)
P_found_job = round(len(df[df['found_job']==1])/len(df),4)
P_no_found_job = round(len(df[df['found_job']==0])/len(df),4)

# p(english|found job)
p_found_e_level_1 = round(len(df[(df['english_level']==1)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_e_level_2 = round(len(df[(df['english_level']==2)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_e_level_3 = round(len(df[(df['english_level']==3)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_e_level_4 = round(len(df[(df['english_level']==4)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_e_level_5 = round(len(df[(df['english_level']==5)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_e_level_6 = round(len(df[(df['english_level']==6)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
# p(english|not found job)
p_not_found_e_level_1 = round(len(df[(df['english_level']==1)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_e_level_2 = round(len(df[(df['english_level']==2)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_e_level_3 = round(len(df[(df['english_level']==3)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_e_level_4 = round(len(df[(df['english_level']==4)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_e_level_5 = round(len(df[(df['english_level']==5)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_e_level_6 = round(len(df[(df['english_level']==6)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)

# P(loan|found job)
p_found_loan_1 = round(len(df[(df['loan_status']==1)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_loan_0 = round(len(df[(df['loan_status']==0)&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
# P(loan|not found job)
p_not_found_loan_1 = round(len(df[(df['loan_status']==1)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_loan_0 = round(len(df[(df['loan_status']==0)&(df['found_job']==0)])/len(df[df['found_job']==0]),4)

# P(highest_graduation|found job)
p_found_graduation_Y = round(len(df[(df['highest_graduation']=='Y')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_graduation_I = round(len(df[(df['highest_graduation']=='I')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_graduation_D = round(len(df[(df['highest_graduation']=='D')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
# P(highest_graduation|not found job)
p_not_found_graduation_Y = round(len(df[(df['highest_graduation']=='Y')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_graduation_I = round(len(df[(df['highest_graduation']=='I')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_graduation_D = round(len(df[(df['highest_graduation']=='D')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)

# P(edu_class|found job)
p_found_class_B = round(len(df[(df['educ_class']=='B')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_class_M = round(len(df[(df['educ_class']=='M')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
p_found_class_D = round(len(df[(df['educ_class']=='D')&(df['found_job']==1)])/len(df[df['found_job']==1]),4)
# P(edu_class|not found job)
p_not_found_class_B = round(len(df[(df['educ_class']=='B')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_class_M = round(len(df[(df['educ_class']=='M')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)
p_not_found_class_D = round(len(df[(df['educ_class']=='D')&(df['found_job']==0)])/len(df[df['found_job']==0]),4)

In [31]:
df_pred = pd.read_excel("native_bayes_pred.xlsx")

In [34]:
result = []
for r in range(len(df_pred)):
    #educ_class
    educ_class = df_pred.iloc[r,0]
    if educ_class == 'B':
        p_found_educ = p_found_class_B
        p_not_found_educ = p_not_found_class_B
    elif educ_class == 'M':
        p_found_educ = p_found_class_M
        p_not_found_educ = p_not_found_class_M
    else:
        p_found_educ = p_found_class_D
        p_not_found_educ = p_not_found_class_D
        
    #highest_graduation
    graduation = df_pred.iloc[r,1]
    if graduation == 'Y':
        p_found_graduation = p_found_graduation_Y
        p_not_found_graduation = p_not_found_graduation_Y
    elif graduation == 'I':
        p_found_graduation = p_found_graduation_I
        p_not_found_graduation = p_not_found_graduation_I
    else:
        p_found_graduation = p_found_graduation_D
        p_not_found_graduation = p_not_found_graduation_D
        
    #loan_status
    loan = df_pred.iloc[r,2]
    if loan == 1:
        p_fond_loan = p_found_loan_1
        p_not_found_loan = p_not_found_loan_1
    else:
        p_fond_loan = p_found_loan_0
        p_not_found_loan = p_not_found_loan_0
    
    #english_level
    english = df_pred.iloc[r,3]
    if english == 1:
        p_found_english = p_found_e_level_1
        p_not_found_english = p_not_found_e_level_1
    elif english == 2:
        p_found_english = p_found_e_level_2
        p_not_found_english = p_not_found_e_level_2
    elif english == 3:
        p_found_english = p_found_e_level_3
        p_not_found_english = p_not_found_e_level_3
    elif english == 4:
        p_found_english = p_found_e_level_4
        p_not_found_english = p_not_found_e_level_4
    elif english == 5:
        p_found_english = p_found_e_level_5
        p_not_found_english = p_not_found_e_level_5
    elif english == 6:
        p_found_english = p_found_e_level_6
        p_not_found_english = p_not_found_e_level_6
        
    #P(found)
    p_found = P_found_job * p_found_educ * p_found_graduation * p_fond_loan * p_found_english
    p_not_found = P_no_found_job * p_not_found_educ * p_not_found_graduation * p_not_found_loan * p_not_found_english
    
    if p_found > p_not_found:
        pred_result = 1
    else:
        pred_result = 0
        
    result.append(pred_result)

In [37]:
pd.DataFrame(result).to_excel("nb_pred.xlsx")